name: Build geoip.dat and geosite.dat

on:
  schedule:
    - cron: "0 0 * * 3"
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout geoip
        uses: actions/checkout@v2
        with:
          repository: v2fly/geoip
          path: repos/geoip
      - name: Checkout domain-list-community
        uses: actions/checkout@v2
        with:
          repository: v2fly/domain-list-community
          path: repos/domain-list-community
      - name: Set up Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17.1
        id: go
      - name: Run build.sh
        run: |
          # Set GOPATH and release variables
          export TAG_NAME=$(date +%Y%m%d%H%M) ;
          export NAME=$(date +%Y%m%d%H%M) ;
          export GOPATH=$(dirname $GITHUB_WORKSPACE) ;
          export PATH="$(dirname $GITHUB_WORKSPACE)/bin:$PATH" ;
          mkdir -p "$GITHUB_WORKSPACE/geoip"
          curl -L "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country-CSV&license_key=$MAXMIND_LICENSE_KEY&suffix=zip" -o "$GITHUB_WORKSPACE/geoip/GeoLite2-Country-CSV.zip"
          bash $GITHUB_WORKSPACE/build.sh
          zip all.zip *.dat *.ipset dnsmasq-blacklist.conf
          tar -zcvf all.tar.gz *.dat *.ipset dnsmasq-blacklist.conf
        shell: bash
        env:
          MAXMIND_LICENSE_KEY: ${{ secrets.MAXMIND_LICENSE_KEY }}
      - name: Release
        uses: xresloader/upload-to-github-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "*.dat;*.ipset;*.sha256sum;dnsmasq-blacklist.conf;*.zip;*.tar.gz"
          tags: true
          draft: false
          overwrite: true
          tag_name: latest
          update_latest_release: true
          verbose: true
